//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class Account
    {
        #region Primitive Properties
    
        public string Login
        {
            get; set;
        }
    
        public string Email
        {
            get; set;
        }
    
        public string Password
        {
            get; set;
        }

        #endregion

    }
}
