//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    using System;
    using System.Collections.Generic;
    
    using System.Data.Entity.ModelConfiguration;
    using global::Fantasy.API.DataAccess.Configurations;
    using System.ComponentModel.DataAnnotations.Schema;
    internal sealed class AccountfriendsMapping : EntityTypeConfiguration<AccountFriends>
    {
                public AccountfriendsMapping()
                {
                    string dbSchema = DataLayerEnvironment.GetInstance().FantasyMssqlProperties.DbSchema; 
    		            this.HasKey(t => new {t.AccountFriendsId, t.AccountLogin, t.AccountLogin1});	
    		            this.ToTable("AccountFriends",dbSchema);
                        this.Property(t => t.AccountFriendsId).HasColumnName("AccountFriendsId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
                        this.Property(t => t.AccountLogin).HasColumnName("AccountLogin").IsRequired().HasMaxLength(50);
                        this.Property(t => t.AccountLogin1).HasColumnName("AccountLogin1").IsRequired().HasMaxLength(50);
    
                }
    }
}
