//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    using System;
    using System.Collections.Generic;
    
    using System.Data.Entity.ModelConfiguration;
    using global::Fantasy.API.DataAccess.Configurations;
    using System.ComponentModel.DataAnnotations.Schema;
    internal sealed class ContestlineupMapping : EntityTypeConfiguration<ContestLineup>
    {
                public ContestlineupMapping()
                {
                    string dbSchema = DataLayerEnvironment.GetInstance().FantasyMssqlProperties.DbSchema; 
    		            this.HasKey(t => new {t.ContestLineupId, t.ContestId, t.LineUpId});	
    		            this.ToTable("ContestLineup",dbSchema);
                        this.Property(t => t.ContestLineupId).HasColumnName("ContestLineupId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
                        this.Property(t => t.ContestId).HasColumnName("ContestId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
                        this.Property(t => t.LineUpId).HasColumnName("LineUpId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
    
                }
    }
}
