//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class ContestType
    {
        #region Primitive Properties
    
        public long ContestTypeId
        {
            get; set;
        }
    
        public string Type
        {
            get; set;
        }

        #endregion

        #region Navigation Properties
    
        public ICollection<Contest> Contests
        {
            get
            {
                if (_contests == null)
                {
                    var newCollection = new FixupCollection<Contest>();
                    newCollection.CollectionChanged += FixupContests;
                    _contests = newCollection;
                }
                return _contests;
            }
            set
            {
                if (!ReferenceEquals(_contests, value))
                {
                    var previousValue = _contests as FixupCollection<Contest>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupContests;
                    }
                    _contests = value;
                    var newValue = value as FixupCollection<Contest>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupContests;
                    }
                }
            }
        }
        private ICollection<Contest> _contests;

        #endregion

        #region Association Fixup
    
        private void FixupContests(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Contest item in e.NewItems)
                {
                    item.ContestType = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Contest item in e.OldItems)
                {
                    if (ReferenceEquals(item.ContestType, this))
                    {
                        item.ContestType = null;
                    }
                }
            }
        }

        #endregion

    }
}
