//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    using System;
    using System.Collections.Generic;
    
    using System.Data.Entity.ModelConfiguration;
    using global::Fantasy.API.DataAccess.Configurations;
    using System.ComponentModel.DataAnnotations.Schema;
    internal sealed class ContestgameMapping : EntityTypeConfiguration<ContestGame>
    {
                public ContestgameMapping()
                {
                    string dbSchema = DataLayerEnvironment.GetInstance().FantasyMssqlProperties.DbSchema; 
    		            this.HasKey(t => new {t.ContestId, t.GameId, t.ContestGameId});	
    		            this.ToTable("ContestGame",dbSchema);
                        this.Property(t => t.ContestId).HasColumnName("ContestId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
                        this.Property(t => t.GameId).HasColumnName("GameId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
                        this.Property(t => t.ContestGameId).HasColumnName("ContestGameId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
    
                }
    }
}
