//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class Contest
    {
        #region Primitive Properties
    
        public int ContestId
        {
            get; set;
        }
    
        public int ContestTypeId
        {
    get { return _contestTypeId; }
            set
            {
                if (_contestTypeId != value)
                {
                    if (ContestType != null && ContestType.ContestTypeId != value)
                    {
                        ContestType = null;
                    }
                    _contestTypeId = value;
                }
            }
        }
        private int _contestTypeId;
    
        public string Name
        {
            get; set;
        }
    
        public int SignedUp
        {
            get; set;
        }
    
        public int MaxCapacity
        {
            get; set;
        }
    
        public double EntryFee
        {
            get; set;
        }
    
        public double SalaryCap
        {
            get; set;
        }

        #endregion

        #region Navigation Properties
    
        public ContestType ContestType
        {
            get { return _contestType; }
            set
            {
                if (!ReferenceEquals(_contestType, value))
                {
                    var previousValue = _contestType;
                    _contestType = value;
                    FixupContestType(previousValue);
                }
            }
        }
        private ContestType _contestType;
    
        public ICollection<Game> Games
        {
            get
            {
                if (_games == null)
                {
                    var newCollection = new FixupCollection<Game>();
                    newCollection.CollectionChanged += FixupGames;
                    _games = newCollection;
                }
                return _games;
            }
            set
            {
                if (!ReferenceEquals(_games, value))
                {
                    var previousValue = _games as FixupCollection<Game>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupGames;
                    }
                    _games = value;
                    var newValue = value as FixupCollection<Game>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupGames;
                    }
                }
            }
        }
        private ICollection<Game> _games;
    
        public ICollection<LineUp> LineUps
        {
            get
            {
                if (_lineUps == null)
                {
                    var newCollection = new FixupCollection<LineUp>();
                    newCollection.CollectionChanged += FixupLineUps;
                    _lineUps = newCollection;
                }
                return _lineUps;
            }
            set
            {
                if (!ReferenceEquals(_lineUps, value))
                {
                    var previousValue = _lineUps as FixupCollection<LineUp>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLineUps;
                    }
                    _lineUps = value;
                    var newValue = value as FixupCollection<LineUp>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLineUps;
                    }
                }
            }
        }
        private ICollection<LineUp> _lineUps;

        #endregion

        #region Association Fixup
    
        private void FixupContestType(ContestType previousValue)
        {
            if (previousValue != null && previousValue.Contests.Contains(this))
            {
                previousValue.Contests.Remove(this);
            }
    
            if (ContestType != null)
            {
                if (!ContestType.Contests.Contains(this))
                {
                    ContestType.Contests.Add(this);
                }
                if (ContestTypeId != ContestType.ContestTypeId)
                {
                    ContestTypeId = ContestType.ContestTypeId;
                }
            }
        }
    
        private void FixupGames(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Game item in e.NewItems)
                {
                    if (!item.Contests.Contains(this))
                    {
                        item.Contests.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Game item in e.OldItems)
                {
                    if (item.Contests.Contains(this))
                    {
                        item.Contests.Remove(this);
                    }
                }
            }
        }
    
        private void FixupLineUps(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (LineUp item in e.NewItems)
                {
                    if (!item.Contests.Contains(this))
                    {
                        item.Contests.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (LineUp item in e.OldItems)
                {
                    if (item.Contests.Contains(this))
                    {
                        item.Contests.Remove(this);
                    }
                }
            }
        }

        #endregion

    }
}
