//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class Game
    {
        #region Primitive Properties
    
        public long GameId
        {
            get; set;
        }
    
        public System.DateTime Scheduled
        {
            get; set;
        }
    
        public double Humidity
        {
            get; set;
        }
    
        public double Temperture
        {
            get; set;
        }
    
        public long VenueId
        {
    get { return _venueId; }
            set
            {
                if (_venueId != value)
                {
                    if (Venue != null && Venue.VenueId != value)
                    {
                        Venue = null;
                    }
                    _venueId = value;
                }
            }
        }
        private long _venueId;
    
        public long ClimaConditionsId
        {
    get { return _climaConditionsId; }
            set
            {
                if (_climaConditionsId != value)
                {
                    if (ClimaCondition != null && ClimaCondition.ClimaConditionsId != value)
                    {
                        ClimaCondition = null;
                    }
                    _climaConditionsId = value;
                }
            }
        }
        private long _climaConditionsId;

        #endregion

        #region Navigation Properties
    
        public ClimaConditions ClimaCondition
        {
            get { return _climaCondition; }
            set
            {
                if (!ReferenceEquals(_climaCondition, value))
                {
                    var previousValue = _climaCondition;
                    _climaCondition = value;
                    FixupClimaCondition(previousValue);
                }
            }
        }
        private ClimaConditions _climaCondition;
    
        public ICollection<ContestGame> ContestGames
        {
            get
            {
                if (_contestGames == null)
                {
                    var newCollection = new FixupCollection<ContestGame>();
                    newCollection.CollectionChanged += FixupContestGames;
                    _contestGames = newCollection;
                }
                return _contestGames;
            }
            set
            {
                if (!ReferenceEquals(_contestGames, value))
                {
                    var previousValue = _contestGames as FixupCollection<ContestGame>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupContestGames;
                    }
                    _contestGames = value;
                    var newValue = value as FixupCollection<ContestGame>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupContestGames;
                    }
                }
            }
        }
        private ICollection<ContestGame> _contestGames;
    
        public Venue Venue
        {
            get { return _venue; }
            set
            {
                if (!ReferenceEquals(_venue, value))
                {
                    var previousValue = _venue;
                    _venue = value;
                    FixupVenue(previousValue);
                }
            }
        }
        private Venue _venue;
    
        public Team Team
        {
            get { return _team; }
            set
            {
                if (!ReferenceEquals(_team, value))
                {
                    var previousValue = _team;
                    _team = value;
                    FixupTeam(previousValue);
                }
            }
        }
        private Team _team;
    
        public Team Team1
        {
            get { return _team1; }
            set
            {
                if (!ReferenceEquals(_team1, value))
                {
                    var previousValue = _team1;
                    _team1 = value;
                    FixupTeam1(previousValue);
                }
            }
        }
        private Team _team1;

        #endregion

        #region Association Fixup
    
        private void FixupClimaCondition(ClimaConditions previousValue)
        {
            if (previousValue != null && previousValue.Games.Contains(this))
            {
                previousValue.Games.Remove(this);
            }
    
            if (ClimaCondition != null)
            {
                if (!ClimaCondition.Games.Contains(this))
                {
                    ClimaCondition.Games.Add(this);
                }
                if (ClimaConditionsId != ClimaCondition.ClimaConditionsId)
                {
                    ClimaConditionsId = ClimaCondition.ClimaConditionsId;
                }
            }
        }
    
        private void FixupVenue(Venue previousValue)
        {
            if (previousValue != null && previousValue.Games.Contains(this))
            {
                previousValue.Games.Remove(this);
            }
    
            if (Venue != null)
            {
                if (!Venue.Games.Contains(this))
                {
                    Venue.Games.Add(this);
                }
                if (VenueId != Venue.VenueId)
                {
                    VenueId = Venue.VenueId;
                }
            }
        }
    
        private void FixupTeam(Team previousValue)
        {
            if (previousValue != null && previousValue.Games.Contains(this))
            {
                previousValue.Games.Remove(this);
            }
    
            if (Team != null)
            {
                if (!Team.Games.Contains(this))
                {
                    Team.Games.Add(this);
                }
            }
        }
    
        private void FixupTeam1(Team previousValue)
        {
            if (previousValue != null && previousValue.Games1.Contains(this))
            {
                previousValue.Games1.Remove(this);
            }
    
            if (Team1 != null)
            {
                if (!Team1.Games1.Contains(this))
                {
                    Team1.Games1.Add(this);
                }
            }
        }
    
        private void FixupContestGames(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ContestGame item in e.NewItems)
                {
                    item.Game = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ContestGame item in e.OldItems)
                {
                    if (ReferenceEquals(item.Game, this))
                    {
                        item.Game = null;
                    }
                }
            }
        }

        #endregion

    }
}
