//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class Goal
    {
        #region Primitive Properties
    
        public long GoalId
        {
            get; set;
        }
    
        public string Name
        {
            get; set;
        }
    
        public int CompletionCount
        {
            get; set;
        }
    
        public string GoalLogo
        {
            get; set;
        }
    
        public long SportId
        {
    get { return _sportId; }
            set
            {
                if (_sportId != value)
                {
                    if (Sport != null && Sport.SportId != value)
                    {
                        Sport = null;
                    }
                    _sportId = value;
                }
            }
        }
        private long _sportId;

        #endregion

        #region Navigation Properties
    
        public Sport Sport
        {
            get { return _sport; }
            set
            {
                if (!ReferenceEquals(_sport, value))
                {
                    var previousValue = _sport;
                    _sport = value;
                    FixupSport(previousValue);
                }
            }
        }
        private Sport _sport;

        #endregion

        #region Association Fixup
    
        private void FixupSport(Sport previousValue)
        {
            if (previousValue != null && previousValue.Goals.Contains(this))
            {
                previousValue.Goals.Remove(this);
            }
    
            if (Sport != null)
            {
                if (!Sport.Goals.Contains(this))
                {
                    Sport.Goals.Add(this);
                }
                if (SportId != Sport.SportId)
                {
                    SportId = Sport.SportId;
                }
            }
        }

        #endregion

    }
}
