//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DataAccess.Models.MSSQL.Fantasy
{
    public class InjuryPlayer
    {
        #region Primitive Properties
    
        public string PlayerId
        {
            get; set;
        }
    
        public string Status
        {
            get; set;
        }
    
        public string Position
        {
            get; set;
        }
    
        public string PrimaryPosition
        {
            get; set;
        }
    
        public string FirstName
        {
            get; set;
        }
    
        public string LastName
        {
            get; set;
        }
    
        public string JerseyNumber
        {
            get; set;
        }
    
        public string PreferredName
        {
            get; set;
        }
    
        public string InjuryId
        {
    get { return _injuryId; }
            set
            {
                if (_injuryId != value)
                {
                    if (Injury != null && Injury.InjuryId != value)
                    {
                        Injury = null;
                    }
                    _injuryId = value;
                }
            }
        }
        private string _injuryId;
    
        public string InjuryTeamId
        {
    get { return _injuryTeamId; }
            set
            {
                if (_injuryTeamId != value)
                {
                    if (InjuryTeam != null && InjuryTeam.TeamId != value)
                    {
                        InjuryTeam = null;
                    }
                    _injuryTeamId = value;
                }
            }
        }
        private string _injuryTeamId;

        #endregion

        #region Navigation Properties
    
        public Injury Injury
        {
            get { return _injury; }
            set
            {
                if (!ReferenceEquals(_injury, value))
                {
                    var previousValue = _injury;
                    _injury = value;
                    FixupInjury(previousValue);
                }
            }
        }
        private Injury _injury;
    
        public InjuryTeam InjuryTeam
        {
            get { return _injuryTeam; }
            set
            {
                if (!ReferenceEquals(_injuryTeam, value))
                {
                    var previousValue = _injuryTeam;
                    _injuryTeam = value;
                    FixupInjuryTeam(previousValue);
                }
            }
        }
        private InjuryTeam _injuryTeam;

        #endregion

        #region Association Fixup
    
        private void FixupInjury(Injury previousValue)
        {
            if (previousValue != null && previousValue.InjuryPlayers.Contains(this))
            {
                previousValue.InjuryPlayers.Remove(this);
            }
    
            if (Injury != null)
            {
                if (!Injury.InjuryPlayers.Contains(this))
                {
                    Injury.InjuryPlayers.Add(this);
                }
                if (InjuryId != Injury.InjuryId)
                {
                    InjuryId = Injury.InjuryId;
                }
            }
        }
    
        private void FixupInjuryTeam(InjuryTeam previousValue)
        {
            if (previousValue != null && previousValue.InjuryPlayers.Contains(this))
            {
                previousValue.InjuryPlayers.Remove(this);
            }
    
            if (InjuryTeam != null)
            {
                if (!InjuryTeam.InjuryPlayers.Contains(this))
                {
                    InjuryTeam.InjuryPlayers.Add(this);
                }
                if (InjuryTeamId != InjuryTeam.TeamId)
                {
                    InjuryTeamId = InjuryTeam.TeamId;
                }
            }
        }

        #endregion

    }
}
