//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class Injury
    {
        #region Primitive Properties
    
        public long InjuryId
        {
            get; set;
        }
    
        public string Comment
        {
            get; set;
        }
    
        public string Description
        {
            get; set;
        }
    
        public string Status
        {
            get; set;
        }
    
        public System.DateTime StartDate
        {
            get; set;
        }
    
        public System.DateTime UpdateDate
        {
            get; set;
        }

        #endregion

    }
}
