//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace DataAccess.Models.MSSQL.Fantasy
{
    public class Injury
    {
        #region Primitive Properties
    
        public string InjuryId
        {
            get; set;
        }
    
        public string Comment
        {
            get; set;
        }
    
        public string Description
        {
            get; set;
        }
    
        public string Status
        {
            get; set;
        }
    
        public System.DateTime StartDate
        {
            get; set;
        }
    
        public System.DateTime UpdateDate
        {
            get; set;
        }

        #endregion

        #region Navigation Properties
    
        public ICollection<InjuryPlayer> InjuryPlayers
        {
            get
            {
                if (_injuryPlayers == null)
                {
                    var newCollection = new FixupCollection<InjuryPlayer>();
                    newCollection.CollectionChanged += FixupInjuryPlayers;
                    _injuryPlayers = newCollection;
                }
                return _injuryPlayers;
            }
            set
            {
                if (!ReferenceEquals(_injuryPlayers, value))
                {
                    var previousValue = _injuryPlayers as FixupCollection<InjuryPlayer>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupInjuryPlayers;
                    }
                    _injuryPlayers = value;
                    var newValue = value as FixupCollection<InjuryPlayer>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupInjuryPlayers;
                    }
                }
            }
        }
        private ICollection<InjuryPlayer> _injuryPlayers;

        #endregion

        #region Association Fixup
    
        private void FixupInjuryPlayers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (InjuryPlayer item in e.NewItems)
                {
                    item.Injury = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (InjuryPlayer item in e.OldItems)
                {
                    if (ReferenceEquals(item.Injury, this))
                    {
                        item.Injury = null;
                    }
                }
            }
        }

        #endregion

    }
}
