//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class League
    {
        #region Primitive Properties
    
        public long LeagueId
        {
            get; set;
        }
    
        public string Name
        {
            get; set;
        }
    
        public string Alias
        {
            get; set;
        }

        #endregion

        #region Navigation Properties
    
        public ICollection<TeamLeague> TeamLeagues
        {
            get
            {
                if (_teamLeagues == null)
                {
                    var newCollection = new FixupCollection<TeamLeague>();
                    newCollection.CollectionChanged += FixupTeamLeagues;
                    _teamLeagues = newCollection;
                }
                return _teamLeagues;
            }
            set
            {
                if (!ReferenceEquals(_teamLeagues, value))
                {
                    var previousValue = _teamLeagues as FixupCollection<TeamLeague>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupTeamLeagues;
                    }
                    _teamLeagues = value;
                    var newValue = value as FixupCollection<TeamLeague>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupTeamLeagues;
                    }
                }
            }
        }
        private ICollection<TeamLeague> _teamLeagues;

        #endregion

        #region Association Fixup
    
        private void FixupTeamLeagues(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (TeamLeague item in e.NewItems)
                {
                    item.League = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (TeamLeague item in e.OldItems)
                {
                    if (ReferenceEquals(item.League, this))
                    {
                        item.League = null;
                    }
                }
            }
        }

        #endregion

    }
}
