//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class LineUp
    {
        #region Primitive Properties
    
        public long LineUpId
        {
            get; set;
        }
    
        public string AccountLogin
        {
    get { return _accountLogin; }
            set
            {
                if (_accountLogin != value)
                {
                    if (Account != null && Account.Login != value)
                    {
                        Account = null;
                    }
                    _accountLogin = value;
                }
            }
        }
        private string _accountLogin;

        #endregion

        #region Navigation Properties
    
        public Account Account
        {
            get { return _account; }
            set
            {
                if (!ReferenceEquals(_account, value))
                {
                    var previousValue = _account;
                    _account = value;
                    FixupAccount(previousValue);
                }
            }
        }
        private Account _account;
    
        public ICollection<Player> Players
        {
            get
            {
                if (_players == null)
                {
                    var newCollection = new FixupCollection<Player>();
                    newCollection.CollectionChanged += FixupPlayers;
                    _players = newCollection;
                }
                return _players;
            }
            set
            {
                if (!ReferenceEquals(_players, value))
                {
                    var previousValue = _players as FixupCollection<Player>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPlayers;
                    }
                    _players = value;
                    var newValue = value as FixupCollection<Player>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPlayers;
                    }
                }
            }
        }
        private ICollection<Player> _players;
    
        public ICollection<Contest> Contests
        {
            get
            {
                if (_contests == null)
                {
                    var newCollection = new FixupCollection<Contest>();
                    newCollection.CollectionChanged += FixupContests;
                    _contests = newCollection;
                }
                return _contests;
            }
            set
            {
                if (!ReferenceEquals(_contests, value))
                {
                    var previousValue = _contests as FixupCollection<Contest>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupContests;
                    }
                    _contests = value;
                    var newValue = value as FixupCollection<Contest>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupContests;
                    }
                }
            }
        }
        private ICollection<Contest> _contests;

        #endregion

        #region Association Fixup
    
        private void FixupAccount(Account previousValue)
        {
            if (previousValue != null && previousValue.LineUps.Contains(this))
            {
                previousValue.LineUps.Remove(this);
            }
    
            if (Account != null)
            {
                if (!Account.LineUps.Contains(this))
                {
                    Account.LineUps.Add(this);
                }
                if (AccountLogin != Account.Login)
                {
                    AccountLogin = Account.Login;
                }
            }
        }
    
        private void FixupPlayers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Player item in e.NewItems)
                {
                    if (!item.LineUps.Contains(this))
                    {
                        item.LineUps.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Player item in e.OldItems)
                {
                    if (item.LineUps.Contains(this))
                    {
                        item.LineUps.Remove(this);
                    }
                }
            }
        }
    
        private void FixupContests(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Contest item in e.NewItems)
                {
                    if (!item.LineUps.Contains(this))
                    {
                        item.LineUps.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Contest item in e.OldItems)
                {
                    if (item.LineUps.Contains(this))
                    {
                        item.LineUps.Remove(this);
                    }
                }
            }
        }

        #endregion

    }
}
