//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class LineUp
    {
        #region Primitive Properties
    
        public long LineUpId
        {
            get; set;
        }
    
        public string AccountLogin
        {
    get { return _accountLogin; }
            set
            {
                if (_accountLogin != value)
                {
                    if (Account != null && Account.Login != value)
                    {
                        Account = null;
                    }
                    _accountLogin = value;
                }
            }
        }
        private string _accountLogin;
    
        public long PlayerLineupId
        {
            get; set;
        }

        #endregion

        #region Navigation Properties
    
        public Account Account
        {
            get { return _account; }
            set
            {
                if (!ReferenceEquals(_account, value))
                {
                    var previousValue = _account;
                    _account = value;
                    FixupAccount(previousValue);
                }
            }
        }
        private Account _account;
    
        public ICollection<PlayerLineup> PlayerLineup
        {
            get
            {
                if (_playerLineup == null)
                {
                    var newCollection = new FixupCollection<PlayerLineup>();
                    newCollection.CollectionChanged += FixupPlayerLineup;
                    _playerLineup = newCollection;
                }
                return _playerLineup;
            }
            set
            {
                if (!ReferenceEquals(_playerLineup, value))
                {
                    var previousValue = _playerLineup as FixupCollection<PlayerLineup>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPlayerLineup;
                    }
                    _playerLineup = value;
                    var newValue = value as FixupCollection<PlayerLineup>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPlayerLineup;
                    }
                }
            }
        }
        private ICollection<PlayerLineup> _playerLineup;
    
        public ICollection<ContestLineup> ContestLineups
        {
            get
            {
                if (_contestLineups == null)
                {
                    var newCollection = new FixupCollection<ContestLineup>();
                    newCollection.CollectionChanged += FixupContestLineups;
                    _contestLineups = newCollection;
                }
                return _contestLineups;
            }
            set
            {
                if (!ReferenceEquals(_contestLineups, value))
                {
                    var previousValue = _contestLineups as FixupCollection<ContestLineup>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupContestLineups;
                    }
                    _contestLineups = value;
                    var newValue = value as FixupCollection<ContestLineup>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupContestLineups;
                    }
                }
            }
        }
        private ICollection<ContestLineup> _contestLineups;

        #endregion

        #region Association Fixup
    
        private void FixupAccount(Account previousValue)
        {
            if (previousValue != null && previousValue.LineUps.Contains(this))
            {
                previousValue.LineUps.Remove(this);
            }
    
            if (Account != null)
            {
                if (!Account.LineUps.Contains(this))
                {
                    Account.LineUps.Add(this);
                }
                if (AccountLogin != Account.Login)
                {
                    AccountLogin = Account.Login;
                }
            }
        }
    
        private void FixupPlayerLineup(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PlayerLineup item in e.NewItems)
                {
                    item.LineUps = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PlayerLineup item in e.OldItems)
                {
                    if (ReferenceEquals(item.LineUps, this))
                    {
                        item.LineUps = null;
                    }
                }
            }
        }
    
        private void FixupContestLineups(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (ContestLineup item in e.NewItems)
                {
                    item.LineUp = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (ContestLineup item in e.OldItems)
                {
                    if (ReferenceEquals(item.LineUp, this))
                    {
                        item.LineUp = null;
                    }
                }
            }
        }

        #endregion

    }
}
