//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    using System;
    using System.Collections.Generic;
    
    using System.Data.Entity.ModelConfiguration;
    using global::Fantasy.API.DataAccess.Configurations;
    using System.ComponentModel.DataAnnotations.Schema;
    internal sealed class NewsteamMapping : EntityTypeConfiguration<NewsTeam>
    {
                public NewsteamMapping()
                {
                    string dbSchema = DataLayerEnvironment.GetInstance().FantasyMssqlProperties.DbSchema; 
    		            this.HasKey(t => new {t.NewsTeamId, t.TeamId, t.NewsId});	
    		            this.ToTable("NewsTeam",dbSchema);
                        this.Property(t => t.NewsTeamId).HasColumnName("NewsTeamId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.Identity);
                        this.Property(t => t.TeamId).HasColumnName("TeamId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
                        this.Property(t => t.NewsId).HasColumnName("NewsId").HasDatabaseGeneratedOption(DatabaseGeneratedOption.None);
    
                }
    }
}
