//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class NewsTeam
    {
        #region Primitive Properties
    
        public long NewsTeamId
        {
            get; set;
        }
    
        public long TeamId
        {
    get { return _teamId; }
            set
            {
                if (_teamId != value)
                {
                    if (Team != null && Team.TeamId != value)
                    {
                        Team = null;
                    }
                    _teamId = value;
                }
            }
        }
        private long _teamId;
    
        public long NewsId
        {
    get { return _newsId; }
            set
            {
                if (_newsId != value)
                {
                    if (News != null && News.NewsId != value)
                    {
                        News = null;
                    }
                    _newsId = value;
                }
            }
        }
        private long _newsId;

        #endregion

        #region Navigation Properties
    
        public Team Team
        {
            get { return _team; }
            set
            {
                if (!ReferenceEquals(_team, value))
                {
                    var previousValue = _team;
                    _team = value;
                    FixupTeam(previousValue);
                }
            }
        }
        private Team _team;
    
        public News News
        {
            get { return _news; }
            set
            {
                if (!ReferenceEquals(_news, value))
                {
                    var previousValue = _news;
                    _news = value;
                    FixupNews(previousValue);
                }
            }
        }
        private News _news;

        #endregion

        #region Association Fixup
    
        private void FixupTeam(Team previousValue)
        {
            if (previousValue != null && previousValue.NewsTeams.Contains(this))
            {
                previousValue.NewsTeams.Remove(this);
            }
    
            if (Team != null)
            {
                if (!Team.NewsTeams.Contains(this))
                {
                    Team.NewsTeams.Add(this);
                }
                if (TeamId != Team.TeamId)
                {
                    TeamId = Team.TeamId;
                }
            }
        }
    
        private void FixupNews(News previousValue)
        {
            if (previousValue != null && previousValue.NewsTeams.Contains(this))
            {
                previousValue.NewsTeams.Remove(this);
            }
    
            if (News != null)
            {
                if (!News.NewsTeams.Contains(this))
                {
                    News.NewsTeams.Add(this);
                }
                if (NewsId != News.NewsId)
                {
                    NewsId = News.NewsId;
                }
            }
        }

        #endregion

    }
}
