//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class Player
    {
        #region Primitive Properties
    
        public int PlayerId
        {
            get; set;
        }
    
        public string FirstName
        {
            get; set;
        }
    
        public string LastName
        {
            get; set;
        }
    
        public string PreferredName
        {
            get; set;
        }
    
        public int TeamId
        {
    get { return _teamId; }
            set
            {
                if (_teamId != value)
                {
                    if (Team != null && Team.TeamId != value)
                    {
                        Team = null;
                    }
                    _teamId = value;
                }
            }
        }
        private int _teamId;
    
        public int PositionId
        {
    get { return _positionId; }
            set
            {
                if (_positionId != value)
                {
                    if (Position != null && Position.PositionId != value)
                    {
                        Position = null;
                    }
                    _positionId = value;
                }
            }
        }
        private int _positionId;
    
        public double Salary
        {
            get; set;
        }
    
        public string Photo
        {
            get; set;
        }

        #endregion

        #region Navigation Properties
    
        public Team Team
        {
            get { return _team; }
            set
            {
                if (!ReferenceEquals(_team, value))
                {
                    var previousValue = _team;
                    _team = value;
                    FixupTeam(previousValue);
                }
            }
        }
        private Team _team;
    
        public Position Position
        {
            get { return _position; }
            set
            {
                if (!ReferenceEquals(_position, value))
                {
                    var previousValue = _position;
                    _position = value;
                    FixupPosition(previousValue);
                }
            }
        }
        private Position _position;
    
        public ICollection<LineUp> LineUps
        {
            get
            {
                if (_lineUps == null)
                {
                    var newCollection = new FixupCollection<LineUp>();
                    newCollection.CollectionChanged += FixupLineUps;
                    _lineUps = newCollection;
                }
                return _lineUps;
            }
            set
            {
                if (!ReferenceEquals(_lineUps, value))
                {
                    var previousValue = _lineUps as FixupCollection<LineUp>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupLineUps;
                    }
                    _lineUps = value;
                    var newValue = value as FixupCollection<LineUp>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupLineUps;
                    }
                }
            }
        }
        private ICollection<LineUp> _lineUps;

        #endregion

        #region Association Fixup
    
        private void FixupTeam(Team previousValue)
        {
            if (previousValue != null && previousValue.Players.Contains(this))
            {
                previousValue.Players.Remove(this);
            }
    
            if (Team != null)
            {
                if (!Team.Players.Contains(this))
                {
                    Team.Players.Add(this);
                }
                if (TeamId != Team.TeamId)
                {
                    TeamId = Team.TeamId;
                }
            }
        }
    
        private void FixupPosition(Position previousValue)
        {
            if (previousValue != null && previousValue.Players.Contains(this))
            {
                previousValue.Players.Remove(this);
            }
    
            if (Position != null)
            {
                if (!Position.Players.Contains(this))
                {
                    Position.Players.Add(this);
                }
                if (PositionId != Position.PositionId)
                {
                    PositionId = Position.PositionId;
                }
            }
        }
    
        private void FixupLineUps(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (LineUp item in e.NewItems)
                {
                    if (!item.Players.Contains(this))
                    {
                        item.Players.Add(this);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (LineUp item in e.OldItems)
                {
                    if (item.Players.Contains(this))
                    {
                        item.Players.Remove(this);
                    }
                }
            }
        }

        #endregion

    }
}
