//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class Player
    {
        #region Primitive Properties
    
        public long PlayerId
        {
            get; set;
        }
    
        public string FirstName
        {
            get; set;
        }
    
        public string LastName
        {
            get; set;
        }
    
        public string PreferredName
        {
            get; set;
        }
    
        public long TeamId
        {
    get { return _teamId; }
            set
            {
                if (_teamId != value)
                {
                    if (Team != null && Team.TeamId != value)
                    {
                        Team = null;
                    }
                    _teamId = value;
                }
            }
        }
        private long _teamId;
    
        public long PositionId
        {
    get { return _positionId; }
            set
            {
                if (_positionId != value)
                {
                    if (Position != null && Position.PositionId != value)
                    {
                        Position = null;
                    }
                    _positionId = value;
                }
            }
        }
        private long _positionId;
    
        public double Salary
        {
            get; set;
        }
    
        public string Photo
        {
            get; set;
        }

        #endregion

        #region Navigation Properties
    
        public Team Team
        {
            get { return _team; }
            set
            {
                if (!ReferenceEquals(_team, value))
                {
                    var previousValue = _team;
                    _team = value;
                    FixupTeam(previousValue);
                }
            }
        }
        private Team _team;
    
        public Position Position
        {
            get { return _position; }
            set
            {
                if (!ReferenceEquals(_position, value))
                {
                    var previousValue = _position;
                    _position = value;
                    FixupPosition(previousValue);
                }
            }
        }
        private Position _position;
    
        public ICollection<PlayerLineup> PlayerLineups
        {
            get
            {
                if (_playerLineups == null)
                {
                    var newCollection = new FixupCollection<PlayerLineup>();
                    newCollection.CollectionChanged += FixupPlayerLineups;
                    _playerLineups = newCollection;
                }
                return _playerLineups;
            }
            set
            {
                if (!ReferenceEquals(_playerLineups, value))
                {
                    var previousValue = _playerLineups as FixupCollection<PlayerLineup>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupPlayerLineups;
                    }
                    _playerLineups = value;
                    var newValue = value as FixupCollection<PlayerLineup>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupPlayerLineups;
                    }
                }
            }
        }
        private ICollection<PlayerLineup> _playerLineups;
    
        public ICollection<Injury> Injuries
        {
            get
            {
                if (_injuries == null)
                {
                    var newCollection = new FixupCollection<Injury>();
                    newCollection.CollectionChanged += FixupInjuries;
                    _injuries = newCollection;
                }
                return _injuries;
            }
            set
            {
                if (!ReferenceEquals(_injuries, value))
                {
                    var previousValue = _injuries as FixupCollection<Injury>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupInjuries;
                    }
                    _injuries = value;
                    var newValue = value as FixupCollection<Injury>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupInjuries;
                    }
                }
            }
        }
        private ICollection<Injury> _injuries;
    
        public ICollection<NewsPlayer> NewsPlayers
        {
            get
            {
                if (_newsPlayers == null)
                {
                    var newCollection = new FixupCollection<NewsPlayer>();
                    newCollection.CollectionChanged += FixupNewsPlayers;
                    _newsPlayers = newCollection;
                }
                return _newsPlayers;
            }
            set
            {
                if (!ReferenceEquals(_newsPlayers, value))
                {
                    var previousValue = _newsPlayers as FixupCollection<NewsPlayer>;
                    if (previousValue != null)
                    {
                        previousValue.CollectionChanged -= FixupNewsPlayers;
                    }
                    _newsPlayers = value;
                    var newValue = value as FixupCollection<NewsPlayer>;
                    if (newValue != null)
                    {
                        newValue.CollectionChanged += FixupNewsPlayers;
                    }
                }
            }
        }
        private ICollection<NewsPlayer> _newsPlayers;

        #endregion

        #region Association Fixup
    
        private void FixupTeam(Team previousValue)
        {
            if (previousValue != null && previousValue.Players.Contains(this))
            {
                previousValue.Players.Remove(this);
            }
    
            if (Team != null)
            {
                if (!Team.Players.Contains(this))
                {
                    Team.Players.Add(this);
                }
                if (TeamId != Team.TeamId)
                {
                    TeamId = Team.TeamId;
                }
            }
        }
    
        private void FixupPosition(Position previousValue)
        {
            if (previousValue != null && previousValue.Players.Contains(this))
            {
                previousValue.Players.Remove(this);
            }
    
            if (Position != null)
            {
                if (!Position.Players.Contains(this))
                {
                    Position.Players.Add(this);
                }
                if (PositionId != Position.PositionId)
                {
                    PositionId = Position.PositionId;
                }
            }
        }
    
        private void FixupPlayerLineups(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (PlayerLineup item in e.NewItems)
                {
                    item.Player = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (PlayerLineup item in e.OldItems)
                {
                    if (ReferenceEquals(item.Player, this))
                    {
                        item.Player = null;
                    }
                }
            }
        }
    
        private void FixupInjuries(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (Injury item in e.NewItems)
                {
                    item.Player = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Injury item in e.OldItems)
                {
                    if (ReferenceEquals(item.Player, this))
                    {
                        item.Player = null;
                    }
                }
            }
        }
    
        private void FixupNewsPlayers(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (e.NewItems != null)
            {
                foreach (NewsPlayer item in e.NewItems)
                {
                    item.Player = this;
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (NewsPlayer item in e.OldItems)
                {
                    if (ReferenceEquals(item.Player, this))
                    {
                        item.Player = null;
                    }
                }
            }
        }

        #endregion

    }
}
