//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;

namespace Fantasy.API.DataAccess.Models.MSSQL.Fantasy
{
    public class Venue
    {
        #region Primitive Properties
    
        public int VenueId
        {
            get; set;
        }
    
        public string Name
        {
            get; set;
        }
    
        public string Surface
        {
            get; set;
        }
    
        public string State
        {
            get; set;
        }
    
        public string Country
        {
            get; set;
        }

        #endregion

    }
}
